# memory-index-gen — generate MEMORY.md from frontmatter as a build artifact.
#
# Spec: 0.4.0
#
# Reads all top-level *.md files plus all <topic>/README.md rollup parents in
# a memory folder, extracts frontmatter, and emits a MEMORY.md whose bullet
# section is fully derived from frontmatter. Operator-curated preamble lives
# in an optional `_memforge.yaml` next to MEMORY.md.
#
# v0.4.0: emits a fenced competing-claim block per SPEC.md §"Multi-agent
# concurrency / Reader-side competing-claim contract" when the folder has
# any decision_topic group with two or more live members (or an active
# snooze). Canonical serialization is byte-stable for CI byte-match.
#
# Modes:
#   --write   Write the generated MEMORY.md to disk (default).
#   --check   Do not write; exit 1 if checked-in MEMORY.md does not
#             byte-match the generator output. CI-wireable.
#   --print   Print generated content to stdout; do not write.
#
# Defaults: per-cwd memory folder ($USER-claude-projects/memory/) +
# ~/.claude/global-memory/. Override with --path (repeatable).

from __future__ import annotations

import argparse
import datetime as _datetime
import os
import re
import sys
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from memforge.frontmatter import has_frontmatter, parse as _mf_parse  # noqa: E402

try:
    import yaml  # type: ignore
    _HAVE_YAML = True
except ImportError:
    _HAVE_YAML = False


GENERATED_HEADER = (
    "<!-- GENERATED BY memory-index-gen — DO NOT EDIT THE BULLET LIST DIRECTLY. -->\n"
    "<!-- Edit frontmatter in the underlying *.md files; rerun memory-index-gen. -->\n"
    "<!-- Operator-curated preamble lives in `_memforge.yaml` in this folder. -->\n"
)


@dataclass
class MemoryFile:
    path: Path
    rel_path: str
    name: str
    description: str
    tier: str = "index"
    status: str = "active"
    pinned: bool = False
    topic: Optional[str] = None
    last_reviewed: Optional[str] = None
    access_labels: list[str] = field(default_factory=list)
    raw_frontmatter: dict = field(default_factory=dict)

    @property
    def access(self) -> str:
        """Backward-compat string view: comma-joined labels.

        New code should use access_labels (list). Retained because some
        adapters / external scripts read the .access string directly.
        """
        return ",".join(self.access_labels)

    @property
    def is_active_index(self) -> bool:
        if self.tier != "index":
            return False
        if self.status in {"archived", "superseded", "dropped"}:
            return False
        return True


# Hierarchical access tiers (RBAC). Higher rank = stricter.
# Files are visible to a viewer when file_rank <= viewer_rank. Team labels
# (team:<name>) are orthogonal to the hierarchy and require explicit
# membership in --viewer-teams.
ACCESS_TIER_RANK = {
    "public": 0,
    "internal": 1,
    "restricted": 2,
    "privileged": 3,
}


def access_label_rank(label: str) -> Optional[int]:
    if not label:
        return None
    label = label.strip().lower()
    if label.startswith("team:"):
        return None
    return ACCESS_TIER_RANK.get(label)


def is_team_label(label: str) -> bool:
    return bool(label) and label.strip().lower().startswith("team:")


def parse_frontmatter(text: str) -> dict:
    """Compatibility shim. Use memforge.frontmatter.parse() in new code."""
    fm, _ = _mf_parse(text)
    return fm


def extract_topic(tags: list) -> Optional[str]:
    for tag in tags:
        if isinstance(tag, str) and tag.startswith("topic:"):
            return tag.split(":", 1)[1]
    return None


def load_memory_file(path: Path, folder_root: Path) -> Optional[MemoryFile]:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    fm = parse_frontmatter(text)
    if not fm:
        return None
    name = fm.get("name", path.stem)
    description = fm.get("description", "")
    tier = fm.get("tier", "index")
    status = fm.get("status", "active")
    pinned = bool(fm.get("pinned", False))
    tags = fm.get("tags", [])
    if isinstance(tags, str):
        tags = [tags]
    topic = extract_topic(tags) if isinstance(tags, list) else None
    last_reviewed = fm.get("last_reviewed") or fm.get("updated")
    access_raw = fm.get("access", "") or ""
    if isinstance(access_raw, list):
        access_labels = [str(a).strip().lower() for a in access_raw if str(a).strip()]
    elif isinstance(access_raw, str):
        if access_raw.strip():
            access_labels = [a.strip().lower() for a in access_raw.split(",") if a.strip()]
        else:
            access_labels = []
    else:
        access_labels = [str(access_raw).strip().lower()] if str(access_raw).strip() else []
    rel = path.relative_to(folder_root).as_posix()
    return MemoryFile(
        path=path,
        rel_path=rel,
        name=name,
        description=description,
        tier=tier,
        status=status,
        pinned=pinned,
        topic=topic,
        last_reviewed=last_reviewed,
        access_labels=access_labels,
        raw_frontmatter=fm,
    )


def discover_index_files(folder_root: Path) -> list[MemoryFile]:
    """Returns all tier:index MemoryFiles in the folder. Top-level .md files
    + <topic>/README.md rollup parents. Excludes archive/, MEMORY.md itself,
    and files without frontmatter."""
    out: list[MemoryFile] = []
    for p in sorted(folder_root.glob("*.md")):
        if p.name == "MEMORY.md":
            continue
        mf = load_memory_file(p, folder_root)
        if mf and mf.is_active_index:
            out.append(mf)
    for sub in sorted(folder_root.iterdir()):
        if not sub.is_dir():
            continue
        if sub.name in ("archive", ".git"):
            continue
        readme = sub / "README.md"
        if not readme.exists():
            continue
        mf = load_memory_file(readme, folder_root)
        if mf and mf.is_active_index:
            out.append(mf)
    return out


def apply_rbac_filter(
    files: list[MemoryFile],
    viewer_tier: Optional[str],
    viewer_teams: list[str],
) -> list[MemoryFile]:
    """Filter files by RBAC (Phase 1 T6.1; v0.3.1: list-valued access).

    viewer_tier: hierarchical level (public | internal | restricted |
    privileged). None means no filter (operator default; backwards-
    compatible).

    viewer_teams: explicit team membership (e.g., ["team:security",
    "team:ops"]).

    Per-file evaluation when access_labels has both hierarchical and team
    labels, file is visible iff:
      (any hierarchical label rank ≤ viewer_rank) AND
      (no team labels present OR viewer's team-set intersects file's team-set)

    A file with only team labels (no hierarchical) is visible to any viewer
    in any listed team. A file with only hierarchical labels is visible to
    viewers at-or-above the least-restrictive listed rank. A file with no
    access labels at all is visible by default when viewer_tier is None
    (backward-compat) and treated as `internal` when viewer_tier is set.

    Files whose access labels do not parse as known tier or team are
    treated as default-deny (skipped) when --viewer-tier is set.
    """
    if viewer_tier is None and not viewer_teams:
        return files
    viewer_rank = (
        ACCESS_TIER_RANK.get(viewer_tier.lower(), None)
        if viewer_tier
        else None
    )
    teams_lc = {t.lower() for t in viewer_teams}
    out: list[MemoryFile] = []
    for mf in files:
        labels = [lbl.strip().lower() for lbl in mf.access_labels if lbl.strip()]
        if not labels:
            # No access labels: default to `internal` when filter is active.
            if viewer_tier is None:
                out.append(mf)
            elif viewer_rank is not None and viewer_rank >= ACCESS_TIER_RANK["internal"]:
                out.append(mf)
            continue

        team_labels = [lbl for lbl in labels if is_team_label(lbl)]
        tier_labels = [lbl for lbl in labels if not is_team_label(lbl)]

        # Hierarchical gate: pass when any tier label is at or below viewer_rank.
        if tier_labels:
            ranks = [access_label_rank(lbl) for lbl in tier_labels]
            ranks = [r for r in ranks if r is not None]
            if not ranks:
                # All tier labels unrecognized -> default-deny.
                continue
            if viewer_rank is None:
                # Tier label present but viewer didn't specify --viewer-tier:
                # be conservative and require the team gate (if any) to pass.
                tier_pass = False
            else:
                tier_pass = any(r <= viewer_rank for r in ranks)
        else:
            # No tier labels -> tier gate doesn't restrict; only team gate matters.
            tier_pass = True

        # Team gate: pass when no team labels OR viewer is in any listed team.
        if team_labels:
            team_pass = bool(set(team_labels) & teams_lc)
        else:
            team_pass = True

        if tier_pass and team_pass:
            out.append(mf)
    return out


def load_preamble(folder_root: Path) -> dict:
    """Optional operator-curated preamble. Falls back to defaults when
    _memforge.yaml is missing."""
    cfg = folder_root / "_memforge.yaml"
    defaults = {
        "title": "Memory Index",
        "preamble": "",
    }
    if not cfg.exists():
        return defaults
    if not _HAVE_YAML:
        sys.stderr.write(
            f"warning: {cfg} present but PyYAML not installed; using defaults\n"
        )
        return defaults
    try:
        with cfg.open("r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except yaml.YAMLError as exc:
        sys.stderr.write(f"warning: failed to parse {cfg}: {exc}; using defaults\n")
        return defaults
    return {
        "title": data.get("title", defaults["title"]),
        "preamble": data.get("preamble", defaults["preamble"]),
    }


_CLAIM_LIVE_STATUSES = {"active", "proposed", "gated"}
_CLAIM_BEGIN = "# memforge:competing-claims:begin"
_CLAIM_END = "# memforge:competing-claims:end"
_CLAIM_RESERVED_YAML_CHARS = set(":#&*!|>'\"%@`")


def _yaml_escape(value: Any) -> str:
    """Emit a value per the canonical serialization rules:
    single-quoted only when the string contains reserved YAML characters,
    starts with whitespace, ends with whitespace, or starts with a leading
    `-`/`[`/`{`. Otherwise plain. Dates and bools are stringified.
    """
    if value is None:
        return "''"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (_datetime.date, _datetime.datetime)):
        return value.isoformat()
    s = str(value)
    if s == "":
        return "''"
    needs_quote = (
        s != s.strip()
        or s[0] in "-[{"
        or any(c in _CLAIM_RESERVED_YAML_CHARS for c in s)
    )
    if needs_quote:
        return "'" + s.replace("'", "''") + "'"
    return s


def _truncate_first_line(body: str) -> str:
    """Per spec: NFKD normalize first non-empty body line, then take the
    first 117 UTF-8 bytes (split safely on UTF-8 boundary), then append
    the literal three-character string `...` only if any truncation
    occurred."""
    line = ""
    for raw in body.splitlines():
        stripped = raw.strip()
        if stripped:
            line = stripped
            break
    if not line:
        return ""
    normalized = unicodedata.normalize("NFKD", line)
    encoded = normalized.encode("utf-8")
    if len(encoded) <= 117:
        return normalized
    cap = 117
    while cap > 0:
        try:
            truncated = encoded[:cap].decode("utf-8")
            return truncated + "..."
        except UnicodeDecodeError:
            cap -= 1
    return ""


def _read_snooze(folder_root: Path, topic: str) -> Optional[dict[str, Any]]:
    """Return parsed snooze record if the topic has an active snooze, else None."""
    if not _HAVE_YAML:
        return None
    snooze_path = folder_root / ".memforge" / "snoozes" / f"{topic}.yaml"
    if not snooze_path.is_file():
        return None
    try:
        record = yaml.safe_load(snooze_path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return None
    if not isinstance(record, dict):
        return None
    snoozed_until = record.get("snoozed_until")
    if isinstance(snoozed_until, (_datetime.date, _datetime.datetime)):
        snoozed_until = snoozed_until.isoformat()
    if not isinstance(snoozed_until, str):
        return None
    today_iso = _datetime.date.today().isoformat()
    if today_iso > snoozed_until:
        return None  # snooze expired
    return record


def _collect_decision_groups(folder_root: Path) -> dict[str, list[dict[str, Any]]]:
    """Walk all .md files under folder_root (excluding MEMORY.md and archive/),
    parse frontmatter, group memories by decision_topic. Returns
    {topic: [{uid, owner, status, updated, first_line, file_path}, ...]}.
    Only live members (status in {active, proposed, gated}) are included.
    """
    groups: dict[str, list[dict[str, Any]]] = {}
    for path in sorted(folder_root.rglob("*.md")):
        if path.name == "MEMORY.md":
            continue
        if "archive" in path.parts:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if not has_frontmatter(text):
            continue
        fm, body = _mf_parse(text)
        if not fm:
            continue
        topic = fm.get("decision_topic")
        if not topic or not isinstance(topic, str):
            continue
        status = fm.get("status")
        if status not in _CLAIM_LIVE_STATUSES:
            continue
        member = {
            "uid": fm.get("uid", ""),
            "owner": fm.get("owner", ""),
            "status": status,
            "updated": fm.get("updated", ""),
            "first_line": _truncate_first_line(body),
            "file_path": path.relative_to(folder_root).as_posix(),
        }
        groups.setdefault(topic, []).append(member)
    return groups


def render_competing_claims_block(folder_root: Path) -> str:
    """Emit the canonical competing-claim YAML fenced block, or empty string
    if no group qualifies. Byte-stable for CI byte-match.
    """
    groups = _collect_decision_groups(folder_root)
    block_topics: list[tuple[str, list[dict[str, Any]], Optional[dict[str, Any]]]] = []
    for topic in sorted(groups):
        members = groups[topic]
        snooze = _read_snooze(folder_root, topic)
        if len(members) < 2 and snooze is None:
            continue  # nothing to surface
        if len(members) < 2 and snooze is not None:
            continue  # snoozed but no live conflict; orphan-snooze handled by audit
        members_sorted = sorted(
            members,
            key=lambda m: (m.get("updated", "") or ""),
            reverse=True,
        )
        # Tie-break by uid ascending.
        members_sorted = sorted(
            members_sorted,
            key=lambda m: (
                "" if (m.get("updated") or "") else "zz",  # keep dated-first ordering
            ),
        )
        # Two-key sort: updated DESC, uid ASC. Use a tuple key with reverse on first.
        members_sorted = sorted(
            members,
            key=lambda m: (m.get("uid", "") or ""),
        )
        members_sorted = sorted(
            members_sorted,
            key=lambda m: (m.get("updated", "") or ""),
            reverse=True,
        )
        block_topics.append((topic, members_sorted, snooze))

    if not block_topics:
        return ""

    lines: list[str] = [_CLAIM_BEGIN]
    for topic, members, snooze in block_topics:
        lines.append(f"- decision_topic: {_yaml_escape(topic)}")
        if snooze is not None:
            lines.append("  state: snoozed")
            lines.append(f"  snoozed_until: {_yaml_escape(snooze.get('snoozed_until', ''))}")
            lines.append(f"  snooze_reason: {_yaml_escape(snooze.get('snooze_reason', ''))}")
        else:
            lines.append("  state: competing")
        lines.append("  members:")
        for m in members:
            lines.append(f"    - uid: {_yaml_escape(m.get('uid', ''))}")
            lines.append(f"      owner: {_yaml_escape(m.get('owner', ''))}")
            lines.append(f"      status: {_yaml_escape(m.get('status', ''))}")
            lines.append(f"      updated: {_yaml_escape(m.get('updated', ''))}")
            lines.append(f"      first_line: {_yaml_escape(m.get('first_line', ''))}")
            lines.append(f"      file_path: {_yaml_escape(m.get('file_path', ''))}")
    lines.append(_CLAIM_END)
    return "\n".join(lines) + "\n"


def render(folder_root: Path, files: list[MemoryFile]) -> str:
    cfg = load_preamble(folder_root)
    pinned = [f for f in files if f.pinned]
    rest = [f for f in files if not f.pinned]
    rest_sorted = sorted(
        rest,
        key=lambda f: ((f.topic or "zz_untopic"), f.name.lower()),
    )
    lines: list[str] = []
    lines.append(f"# {cfg['title']}\n")
    lines.append("")
    if cfg["preamble"].strip():
        lines.append(cfg["preamble"].rstrip())
        lines.append("")
    lines.append(GENERATED_HEADER.rstrip())
    lines.append("")
    if pinned:
        lines.append("## Pinned")
        lines.append("")
        for mf in sorted(pinned, key=lambda f: f.name.lower()):
            lines.append(_bullet(mf))
        lines.append("")
    if rest_sorted:
        current_topic: Optional[str] = None
        topic_header_emitted = False
        for mf in rest_sorted:
            t = mf.topic or "untopic"
            if t != current_topic:
                if topic_header_emitted:
                    lines.append("")
                lines.append(f"## topic:{t}" if mf.topic else "## (no topic)")
                lines.append("")
                current_topic = t
                topic_header_emitted = True
            lines.append(_bullet(mf))
        lines.append("")
    # v0.4.0+: emit competing-claim block when any decision_topic group has
    # 2+ live members. Empty otherwise.
    claim_block = render_competing_claims_block(folder_root)
    if claim_block:
        lines.append("## Competing claims")
        lines.append("")
        lines.append("```yaml")
        # claim_block already ends with newline; split into lines for the join.
        for cl in claim_block.rstrip("\n").split("\n"):
            lines.append(cl)
        lines.append("```")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _bullet(mf: MemoryFile) -> str:
    desc = mf.description.strip()
    if desc:
        return f"- [{mf.name}]({mf.rel_path}): {desc}"
    return f"- [{mf.name}]({mf.rel_path})"


def default_paths() -> list[Path]:
    out: list[Path] = []
    home = Path.home()
    user = os.environ.get("USER", "")
    if user:
        per_cwd = home / ".claude" / "projects" / f"{user}-claude-projects" / "memory"
        if per_cwd.exists():
            out.append(per_cwd)
    glob = home / ".claude" / "global-memory"
    if glob.exists():
        out.append(glob)
    return out


def process(
    folder: Path,
    mode: str,
    viewer_tier: Optional[str] = None,
    viewer_teams: Optional[list[str]] = None,
) -> int:
    if not folder.exists():
        sys.stderr.write(f"error: folder does not exist: {folder}\n")
        return 2
    files = discover_index_files(folder)
    if viewer_tier is not None or viewer_teams:
        files = apply_rbac_filter(files, viewer_tier, viewer_teams or [])
    output = render(folder, files)
    target = folder / "MEMORY.md"
    if mode == "print":
        sys.stdout.write(output)
        return 0
    if mode == "check":
        existing = target.read_text(encoding="utf-8") if target.exists() else ""
        if existing == output:
            print(f"OK   {folder} ({len(files)} index files)")
            return 0
        print(f"DRIFT {folder} ({len(files)} index files)")
        return 1
    target.write_text(output, encoding="utf-8")
    print(f"WROTE {target} ({len(files)} index files)")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(
        prog="memory-index-gen",
        description="Generate MEMORY.md from frontmatter (Phase 1 T3 + T6.1 RBAC).",
    )
    p.add_argument("--path", action="append", default=[], help="Folder to process (repeatable)")
    g = p.add_mutually_exclusive_group()
    g.add_argument("--write", action="store_const", const="write", dest="mode")
    g.add_argument("--check", action="store_const", const="check", dest="mode")
    g.add_argument("--print", action="store_const", const="print", dest="mode")
    p.set_defaults(mode="write")
    p.add_argument(
        "--viewer-tier",
        choices=("public", "internal", "restricted", "privileged"),
        default=None,
        help=(
            "RBAC: filter MEMORY.md output by viewer hierarchical tier. "
            "Files with access label > viewer tier are excluded. "
            "When unset, no RBAC filter applies (operator default)."
        ),
    )
    p.add_argument(
        "--viewer-teams",
        action="append",
        default=[],
        help=(
            "RBAC team membership (repeatable, e.g. --viewer-teams team:security). "
            "Files with team:<x> access label are visible only when viewer is in "
            "that team. Hierarchical access labels are not affected."
        ),
    )
    args = p.parse_args()

    folders = [Path(p).resolve() for p in args.path] if args.path else default_paths()
    if not folders:
        sys.stderr.write("error: no folders specified and no defaults found\n")
        return 2

    rc = 0
    for f in folders:
        result = process(f, args.mode, args.viewer_tier, args.viewer_teams)
        if result != 0:
            rc = result
    return rc


if __name__ == "__main__":
    sys.exit(main())
